# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-08 13:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='nav_bar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('navigation', models.CharField(max_length=20, verbose_name='Название раздела')),
                ('description', models.TextField(max_length=30, verbose_name='Описание')),
            ],
        ),
    ]
