# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-08 14:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiserpage', '0002_auto_20171008_1327'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='nav_bar',
            options={'verbose_name': 'Навигация', 'verbose_name_plural': 'Навигации'},
        ),
        migrations.AlterField(
            model_name='nav_bar',
            name='description',
            field=models.TextField(default='', max_length=100, verbose_name='Описание'),
        ),
    ]
